pgxc_build_dml_statement was using a hack to set alias of the result relation to eref node in some cases including the case of inherited tables. This was a temporary fix and is no more required. Having this code there was causing some tests in xc_returning to fail. For example
create table xc_int8_tbl(q1 int8, q2 int8);
INSERT INTO xc_int8_tbl VALUES('  123   ','  456');
INSERT INTO xc_int8_tbl VALUES('123   ','4567890123456789');
INSERT INTO xc_int8_tbl VALUES('4567890123456789','123');
INSERT INTO xc_int8_tbl VALUES(+4567890123456789,'4567890123456789');
INSERT INTO xc_int8_tbl VALUES('+4567890123456789','-4567890123456789');

create table fp(f1 int, f2 varchar(255), f3 int) distribute by hash(f1);
create table fp_child (fc int) INHERITS (fp) distribute by hash(f1);

INSERT INTO fp VALUES (1,'test',42), (2,'More', 11), (3,upper('more'), 7+9);
INSERT INTO fp_child VALUES(123,'child',999,-123);

ALTER table fp ADD COLUMN f4 int8 DEFAULT 99;

UPDATE fp SET f4 = f4 + f3 WHERE f4 = 99;
UPDATE fp SET f3 = f3*2  FROM xc_int8_tbl i  WHERE fp.f1 = i.q2;

DELETE FROM fp  USING xc_int8_tbl i  WHERE fp.f1 = i.q1  RETURNING *, fp.f1-fp.f3;
ERROR:  column fp_2.f4_1 does not exist